import { Parisienne } from "next/font/google";
import "./globals.css";

const parisienne = Parisienne({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={parisienne.className}>{children}</body>
    </html>
  );
}
